### ISSUE TITLE
Not a IMU

### ISSUE THREAD

**Issue by unlogisch04** [SlimeVR/slimevr-node#40]
MPU6050_SF is not a IMU this line needs to be removed.
https://github.com/SlimeVR/slimevr-node/blob/b1fd86198406f9265191528940bf008ac9b6d68b/packages/firmware-protocol/src/constants.ts#L41

It was never in the tracker code:
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/fef504e3b40f6990d98ef4f0e86ae8b0b123e37d/src/consts.h#L28

See also discussion 
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/322#discussion_r1544877964

And discussion in https://github.com/SlimeVR/SlimeVR-Server/pull/1100

**Comment by TheDevMinerTV** [comment]
Fixed in #41
